// Database các trường đại học Hàn Quốc
const universities = [
    // ============ SEOUL (Thủ đô) ============
    {
        id: "seoul-national-university",
        name: "Đại học Quốc gia Seoul",
        nameKr: "서울대학교",
        nameEn: "Seoul National University (SNU)",
        region: "Seoul",
        type: "Công lập",
        tier: "SKY",
        ranking: 1,
        established: 1946,
        website: "http://www.snu.ac.kr",
        description: "Trường đại học hàng đầu Hàn Quốc, thuộc nhóm SKY danh giá. SNU là biểu tượng của nền giáo dục Hàn Quốc với chất lượng đào tạo xuất sắc và nghiên cứu đẳng cấp thế giới.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "3,000 - 5,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3-4",
        englishRequired: "IELTS 6.0+ / TOEFL 80+",
        scholarship: ["GKS (Học bổng chính phủ)", "Học bổng SNU Global", "Học bổng dành cho sinh viên xuất sắc"],
        popularFor: ["Khoa học máy tính", "Kinh tế", "Luật", "Y khoa", "Khoa học xã hội"],
        studentCount: "30,000+",
        internationalStudentRatio: "10%",
        vietnameseStudents: "Có cộng đồng du học sinh Việt Nam đông đảo",
        address: "1 Gwanak-ro, Gwanak-gu, Seoul",
        image: "https://upload.wikimedia.org/wikipedia/en/3/3c/Seoul_National_University_emblem.svg",
        coordinates: { lat: 37.4602, lng: 126.9514 },
        featured: true,
        tags: ["SKY", "top-1", "cong-lap", "hoc-bong-gks"]
    },
    {
        id: "korea-university",
        name: "Đại học Korea",
        nameKr: "고려대학교",
        nameEn: "Korea University",
        region: "Seoul",
        type: "Tư thục",
        tier: "SKY",
        ranking: 2,
        established: 1905,
        website: "http://www.korea.ac.kr",
        description: "Một trong 3 trường thuộc nhóm SKY, nổi tiếng với chương trình đào tạo Kinh tế, Luật và Quản trị Kinh doanh hàng đầu Hàn Quốc.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "5,000 - 8,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3-4",
        englishRequired: "IELTS 6.0+ / TOEFL 80+",
        scholarship: ["Học bổng Global Korea", "Học bổng KU Excellence", "Học bổng Pony Chung (riêng cho sinh viên Việt Nam)"],
        popularFor: ["Kinh tế", "Luật", "Quản trị kinh doanh", "Báo chí", "Khoa học chính trị"],
        studentCount: "33,000+",
        internationalStudentRatio: "12%",
        vietnameseStudents: "Rất đông, có hội sinh viên Việt Nam tại KU",
        address: "145 Anam-ro, Seongbuk-gu, Seoul",
        image: "https://upload.wikimedia.org/wikipedia/en/7/7e/Korea_University_emblem.svg",
        coordinates: { lat: 37.5895, lng: 127.0322 },
        featured: true,
        tags: ["SKY", "top-2", "tu-thuc", "kinh-te"]
    },
    {
        id: "yonsei-university",
        name: "Đại học Yonsei",
        nameKr: "연세대학교",
        nameEn: "Yonsei University",
        region: "Seoul",
        type: "Tư thục",
        tier: "SKY",
        ranking: 3,
        established: 1885,
        website: "http://www.yonsei.ac.kr",
        description: "Trường đại học tư thục lâu đời và danh giá nhất Hàn Quốc, thuộc nhóm SKY, nổi tiếng với chương trình quốc tế hóa cao và Underwood International College.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "6,000 - 10,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3-4 (hoặc có thể dùng IELTS/TOEFL)",
        englishRequired: "IELTS 6.5+ / TOEFL 90+",
        scholarship: ["Học bổng Yonsei Global", "Học bổng UIC", "Học bổng dành cho sinh viên châu Á"],
        popularFor: ["Y khoa", "Kinh tế quốc tế", "Quan hệ quốc tế", "Khoa học xã hội", "Âm nhạc"],
        studentCount: "38,000+",
        internationalStudentRatio: "15%",
        vietnameseStudents: "Cộng đồng sinh viên Việt Nam lớn mạnh",
        address: "50 Yonsei-ro, Seodaemun-gu, Seoul",
        image: "https://upload.wikimedia.org/wikipedia/en/5/58/Yonsei_University_emblem.svg",
        coordinates: { lat: 37.5665, lng: 126.9390 },
        featured: true,
        tags: ["SKY", "top-3", "tu-thuc", "y-khoa", "quoc-te"]
    },
    {
        id: "sungkyunkwan-university",
        name: "Đại học Sungkyunkwan (SKKU)",
        nameKr: "성균관대학교",
        nameEn: "Sungkyunkwan University (SKKU)",
        region: "Seoul",
        type: "Tư thục",
        tier: "Top 10",
        ranking: 4,
        established: 1398,
        website: "http://www.skku.edu",
        description: "Trường đại học lâu đời nhất châu Á (thành lập năm 1398), hợp tác chiến lược với tập đoàn Samsung. Nổi tiếng về Kỹ thuật, Công nghệ và Kinh doanh.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "5,000 - 9,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3-4",
        englishRequired: "IELTS 6.0+ / TOEFL 80+",
        scholarship: ["Học bổng Samsung-SKKU", "Học bổng Global SKKU", "Học bổng dành cho sinh viên quốc tế xuất sắc"],
        popularFor: ["Kỹ thuật", "Công nghệ thông tin", "Kinh doanh", "Quản lý", "Khoa học máy tính"],
        studentCount: "28,000+",
        internationalStudentRatio: "12%",
        vietnameseStudents: "Đông đảo, đặc biệt ngành Kỹ thuật và CNTT",
        address: "25-2 Sungkyunkwan-ro, Jongno-gu, Seoul",
        image: "https://upload.wikimedia.org/wikipedia/en/6/6a/Sungkyunkwan_University_emblem.svg",
        coordinates: { lat: 37.5859, lng: 126.9942 },
        featured: true,
        tags: ["top-10", "tu-thuc", "samsung", "ky-thuat", "cong-nghe"]
    },
    {
        id: "hanyang-university",
        name: "Đại học Hanyang",
        nameKr: "한양대학교",
        nameEn: "Hanyang University",
        region: "Seoul",
        type: "Tư thục",
        tier: "Top 10",
        ranking: 5,
        established: 1939,
        website: "http://www.hanyang.ac.kr",
        description: "Trường đại học kỹ thuật hàng đầu Hàn Quốc, đặc biệt mạnh về Kỹ thuật Xây dựng, Cơ khí và Kiến trúc. Nằm ở trung tâm Seoul.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "5,000 - 8,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3-4",
        englishRequired: "IELTS 6.0+ / TOEFL 80+",
        scholarship: ["Học bổng Hanyang Global", "Học bổng Hanyang Excellence", "Học bổng dành cho sinh viên ASEAN"],
        popularFor: ["Kỹ thuật xây dựng", "Cơ khí", "Kiến trúc", "Khoa học máy tính", "Kinh tế"],
        studentCount: "25,000+",
        internationalStudentRatio: "10%",
        vietnameseStudents: "Nhiều sinh viên theo học ngành Kỹ thuật",
        address: "222 Wangsimni-ro, Seongdong-gu, Seoul",
        image: "https://upload.wikimedia.org/wikipedia/en/3/3a/Hanyang_University_emblem.svg",
        coordinates: { lat: 37.5590, lng: 127.0440 },
        featured: true,
        tags: ["top-10", "tu-thuc", "ky-thuat", "kien-truc"]
    },
    {
        id: "ewha-womans-university",
        name: "Đại học Nữ Ewha",
        nameKr: "이화여자대학교",
        nameEn: "Ewha Womans University",
        region: "Seoul",
        type: "Tư thục",
        tier: "Top 10",
        ranking: 6,
        established: 1886,
        website: "http://www.ewha.ac.kr",
        description: "Trường đại học nữ danh giá nhất Hàn Quốc, nổi tiếng với chương trình đào tạo Nhân văn, Khoa học xã hội và Nghệ thuật xuất sắc.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "5,000 - 8,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3-4",
        englishRequired: "IELTS 6.0+ / TOEFL 80+",
        scholarship: ["Học bổng Ewha Global", "Học bổng Ewha International", "Học bổng dành cho nữ sinh viên châu Á"],
        popularFor: ["Nhân văn", "Khoa học xã hội", "Thiết kế thời trang", "Âm nhạc", "Quan hệ quốc tế"],
        studentCount: "20,000+",
        internationalStudentRatio: "14%",
        vietnameseStudents: "Đông đảo nữ sinh Việt Nam theo học",
        address: "52 Ewhayeodae-gil, Seodaemun-gu, Seoul",
        image: "https://upload.wikimedia.org/wikipedia/en/e/ed/Ewha_Womans_University_emblem.svg",
        coordinates: { lat: 37.5659, lng: 126.9414 },
        featured: true,
        tags: ["top-10", "tu-thuc", "nu-sinh", "nghe-thuat"]
    },
    {
        id: "sogang-university",
        name: "Đại học Sogang",
        nameKr: "서강대학교",
        nameEn: "Sogang University",
        region: "Seoul",
        type: "Tư thục",
        tier: "Top 10",
        ranking: 7,
        established: 1960,
        website: "http://www.sogang.ac.kr",
        description: "Trường đại học Công giáo danh tiếng, nổi tiếng với chất lượng đào tạo Kinh doanh, Kinh tế và Truyền thông xuất sắc tại trung tâm Seoul.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "5,000 - 8,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3-4",
        englishRequired: "IELTS 6.0+ / TOEFL 80+",
        scholarship: ["Học bổng Sogang Global", "Học bổng Sogang International", "Học bổng dành cho sinh viên Công giáo"],
        popularFor: ["Kinh doanh", "Kinh tế", "Truyền thông", "Quan hệ quốc tế", "Công nghệ thông tin"],
        studentCount: "15,000+",
        internationalStudentRatio: "10%",
        vietnameseStudents: "Có cộng đồng sinh viên Việt Nam",
        address: "35 Baekbeom-ro, Mapo-gu, Seoul",
        image: "https://upload.wikimedia.org/wikipedia/en/7/7a/Sogang_University_emblem.svg",
        coordinates: { lat: 37.5512, lng: 126.9400 },
        featured: false,
        tags: ["top-10", "tu-thuc", "kinh-doanh", "truyen-thong"]
    },
    {
        id: "chung-ang-university",
        name: "Đại học Chung-Ang",
        nameKr: "중앙대학교",
        nameEn: "Chung-Ang University (CAU)",
        region: "Seoul",
        type: "Tư thục",
        tier: "Top 20",
        ranking: 8,
        established: 1918,
        website: "http://www.cau.ac.kr",
        description: "Trường đại học tư thục danh tiếng, đặc biệt nổi tiếng với các chương trình Nghệ thuật, Điện ảnh và Truyền thông hàng đầu Hàn Quốc.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "5,000 - 8,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3-4",
        englishRequired: "IELTS 6.0+ / TOEFL 80+",
        scholarship: ["Học bổng CAU Global", "Học bổng CAU Excellence", "Học bổng dành cho sinh viên quốc tế"],
        popularFor: ["Điện ảnh", "Truyền thông", "Nghệ thuật biểu diễn", "Báo chí", "Kinh doanh"],
        studentCount: "22,000+",
        internationalStudentRatio: "12%",
        vietnameseStudents: "Rất đông, đặc biệt ngành Truyền thông và Nghệ thuật",
        address: "84 Heukseok-ro, Dongjak-gu, Seoul",
        image: "https://upload.wikimedia.org/wikipedia/en/2/2c/Chung-Ang_University_emblem.svg",
        coordinates: { lat: 37.5053, lng: 126.9568 },
        featured: true,
        tags: ["top-20", "tu-thuc", "nghe-thuat", "dien-anh", "truyen-thong"]
    },
    {
        id: "kyung-hee-university",
        name: "Đại học Kyung Hee",
        nameKr: "경희대학교",
        nameEn: "Kyung Hee University",
        region: "Seoul",
        type: "Tư thục",
        tier: "Top 10",
        ranking: 9,
        established: 1949,
        website: "http://www.khu.ac.kr",
        description: "Trường đại học tư thục hàng đầu với khuôn viên đẹp nhất Hàn Quốc, nổi tiếng với ngành Y học cổ truyền, Khách sạn - Du lịch và Quan hệ quốc tế.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "5,000 - 9,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3-4",
        englishRequired: "IELTS 6.0+ / TOEFL 80+",
        scholarship: ["Học bổng Kyung Hee Global", "Học bổng Kyung Hee Dream", "Học bổng dành cho sinh viên quốc tế xuất sắc"],
        popularFor: ["Y học cổ truyền Hàn", "Khách sạn - Du lịch", "Quan hệ quốc tế", "Kinh doanh quốc tế", "Khoa học thể thao"],
        studentCount: "33,000+",
        internationalStudentRatio: "13%",
        vietnameseStudents: "Cộng đồng sinh viên Việt Nam rất đông",
        address: "26 Kyungheedae-ro, Dongdaemun-gu, Seoul",
        image: "https://upload.wikimedia.org/wikipedia/en/0/0f/Kyung_Hee_University_emblem.svg",
        coordinates: { lat: 37.5966, lng: 127.0537 },
        featured: true,
        tags: ["top-10", "tu-thuc", "y-hoc-co-truyen", "khach-san-du-lich"]
    },
    {
        id: "hongik-university",
        name: "Đại học Hongik",
        nameKr: "홍익대학교",
        nameEn: "Hongik University",
        region: "Seoul",
        type: "Tư thục",
        tier: "Top 20",
        ranking: 10,
        established: 1946,
        website: "http://www.hongik.ac.kr",
        description: "Trường đại học nghệ thuật và thiết kế hàng đầu Hàn Quốc, nổi tiếng với chương trình Kiến trúc, Mỹ thuật và Thiết kế công nghiệp.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "5,000 - 8,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3-4",
        englishRequired: "IELTS 5.5+ / TOEFL 80+",
        scholarship: ["Học bổng Hongik Global", "Học bổng Hongik Excellence", "Học bổng dành cho sinh viên nghệ thuật"],
        popularFor: ["Thiết kế công nghiệp", "Kiến trúc", "Mỹ thuật", "Thiết kế đồ họa", "Hoạt hình"],
        studentCount: "20,000+",
        internationalStudentRatio: "10%",
        vietnameseStudents: "Nhiều sinh viên theo học ngành Thiết kế",
        address: "94 Wausan-ro, Mapo-gu, Seoul",
        image: "https://upload.wikimedia.org/wikipedia/en/4/48/Hongik_University_emblem.svg",
        coordinates: { lat: 37.5517, lng: 126.9268 },
        featured: false,
        tags: ["top-20", "tu-thuc", "thiet-ke", "nghe-thuat", "kien-truc"]
    },
    {
        id: "sejong-university",
        name: "Đại học Sejong",
        nameKr: "세종대학교",
        nameEn: "Sejong University",
        region: "Seoul",
        type: "Tư thục",
        tier: "Top 20",
        ranking: 11,
        established: 1940,
        website: "http://www.sejong.ac.kr",
        description: "Trường đại học tư thục chất lượng cao, nổi tiếng với ngành Khách sạn - Du lịch, Khiêu vũ và Nghệ thuật biểu diễn. Đặc biệt được sinh viên Việt Nam ưa chuộng.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "5,000 - 8,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3",
        englishRequired: "IELTS 5.5+ / TOEFL 80+",
        scholarship: ["Học bổng Sejong Global", "Học bổng Sejong Dream", "Học bổng dành cho sinh viên Việt Nam"],
        popularFor: ["Khách sạn - Du lịch", "Khiêu vũ", "Nghệ thuật biểu diễn", "Khoa học máy tính", "Kinh doanh quốc tế"],
        studentCount: "18,000+",
        internationalStudentRatio: "15%",
        vietnameseStudents: "Rất đông, một trong những trường có đông sinh viên Việt Nam nhất",
        address: "209 Neungdong-ro, Gwangjin-gu, Seoul",
        image: "https://upload.wikimedia.org/wikipedia/en/1/18/Sejong_University_emblem.svg",
        coordinates: { lat: 37.5505, lng: 127.0740 },
        featured: true,
        tags: ["top-20", "tu-thuc", "khach-san-du-lich", "nghe-thuat-bieu-dien"]
    },
    {
        id: "dongguk-university",
        name: "Đại học Dongguk",
        nameKr: "동국대학교",
        nameEn: "Dongguk University",
        region: "Seoul",
        type: "Tư thục",
        tier: "Top 20",
        ranking: 12,
        established: 1906,
        website: "http://www.dongguk.ac.kr",
        description: "Trường đại học Phật giáo danh tiếng, nổi tiếng với ngành Điện ảnh, Nghệ thuật biểu diễn và Khoa học xã hội.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "4,500 - 7,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3-4",
        englishRequired: "IELTS 5.5+ / TOEFL 80+",
        scholarship: ["Học bổng Dongguk Global", "Học bổng Dongguk International", "Học bổng dành cho sinh viên Phật tử"],
        popularFor: ["Điện ảnh", "Nghệ thuật biểu diễn", "Triết học Phật giáo", "Khoa học xã hội", "Báo chí"],
        studentCount: "18,000+",
        internationalStudentRatio: "10%",
        vietnameseStudents: "Có cộng đồng sinh viên Việt Nam",
        address: "30 Pildong-ro 1-gil, Jung-gu, Seoul",
        image: "https://upload.wikimedia.org/wikipedia/en/a/a9/Dongguk_University_emblem.svg",
        coordinates: { lat: 37.5584, lng: 126.9983 },
        featured: false,
        tags: ["top-20", "tu-thuc", "dien-anh", "nghe-thuat"]
    },
    {
        id: "sookmyung-womens-university",
        name: "Đại học Nữ Sookmyung",
        nameKr: "숙명여자대학교",
        nameEn: "Sookmyung Women's University",
        region: "Seoul",
        type: "Tư thục",
        tier: "Top 30",
        ranking: 13,
        established: 1906,
        website: "http://www.sookmyung.ac.kr",
        description: "Trường đại học nữ danh tiếng thứ hai tại Hàn Quốc, với thế mạnh về Ngôn ngữ, Kinh doanh quốc tế và Dược.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "4,500 - 7,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3-4",
        englishRequired: "IELTS 5.5+ / TOEFL 80+",
        scholarship: ["Học bổng Sookmyung Global", "Học bổng Sookmyung International", "Học bổng dành cho nữ sinh quốc tế"],
        popularFor: ["Ngôn ngữ Hàn", "Kinh doanh quốc tế", "Dược", "Quan hệ quốc tế", "Thiết kế"],
        studentCount: "10,000+",
        internationalStudentRatio: "12%",
        vietnameseStudents: "Đông đảo nữ sinh Việt Nam",
        address: "100 Cheongpa-ro 47-gil, Yongsan-gu, Seoul",
        image: "https://upload.wikimedia.org/wikipedia/en/4/48/Sookmyung_Women%27s_University_emblem.svg",
        coordinates: { lat: 37.5459, lng: 126.9697 },
        featured: false,
        tags: ["tu-thuc", "nu-sinh", "ngon-ngu"]
    },
    {
        id: "konkuk-university",
        name: "Đại học Konkuk",
        nameKr: "건국대학교",
        nameEn: "Konkuk University",
        region: "Seoul",
        type: "Tư thục",
        tier: "Top 20",
        ranking: 14,
        established: 1946,
        website: "http://www.konkuk.ac.kr",
        description: "Trường đại học tư thục với khuôn viên rộng đẹp ven sông Hàn, nổi tiếng với ngành Thú y, Khoa học đời sống và Kinh doanh.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "4,500 - 7,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3-4",
        englishRequired: "IELTS 5.5+ / TOEFL 80+",
        scholarship: ["Học bổng Konkuk Global", "Học bổng Konkuk Star", "Học bổng dành cho sinh viên quốc tế"],
        popularFor: ["Thú y", "Khoa học đời sống", "Kinh doanh", "Kiến trúc", "Công nghệ sinh học"],
        studentCount: "25,000+",
        internationalStudentRatio: "10%",
        vietnameseStudents: "Có cộng đồng sinh viên Việt Nam",
        address: "120 Neungdong-ro, Gwangjin-gu, Seoul",
        image: "https://upload.wikimedia.org/wikipedia/en/6/63/Konkuk_University_emblem.svg",
        coordinates: { lat: 37.5431, lng: 127.0789 },
        featured: false,
        tags: ["top-20", "tu-thuc", "thu-y", "cong-nghe-sinh-hoc"]
    },
    {
        id: "kookmin-university",
        name: "Đại học Kookmin",
        nameKr: "국민대학교",
        nameEn: "Kookmin University",
        region: "Seoul",
        type: "Tư thục",
        tier: "Top 30",
        ranking: 15,
        established: 1946,
        website: "http://www.kookmin.ac.kr",
        description: "Trường đại học tư thục với thế mạnh về Thiết kế, Kỹ thuật Ô tô và Kiến trúc.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "4,500 - 7,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3",
        englishRequired: "IELTS 5.5+ / TOEFL 80+",
        scholarship: ["Học bổng Kookmin Global", "Học bổng Kookmin Excellence"],
        popularFor: ["Thiết kế", "Kỹ thuật ô tô", "Kiến trúc", "Khoa học máy tính", "Kinh doanh"],
        studentCount: "18,000+",
        internationalStudentRatio: "10%",
        vietnameseStudents: "Nhiều sinh viên ngành Thiết kế và Kỹ thuật",
        address: "77 Jeongneung-ro, Seongbuk-gu, Seoul",
        image: "https://upload.wikimedia.org/wikipedia/en/d/d2/Kookmin_University_emblem.svg",
        coordinates: { lat: 37.6101, lng: 126.9974 },
        featured: false,
        tags: ["tu-thuc", "thiet-ke", "ky-thuat-o-to"]
    },
    {
        id: "university-of-seoul",
        name: "Đại học Seoul",
        nameKr: "서울시립대학교",
        nameEn: "University of Seoul (UOS)",
        region: "Seoul",
        type: "Công lập",
        tier: "Top 20",
        ranking: 16,
        established: 1918,
        website: "http://www.uos.ac.kr",
        description: "Trường đại học công lập của thành phố Seoul, nổi tiếng với chất lượng đào tạo tốt với học phí thấp, đặc biệt các ngành Khoa học đô thị và Kinh tế.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "2,500 - 4,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3-4",
        englishRequired: "IELTS 5.5+ / TOEFL 80+",
        scholarship: ["Học bổng UOS Global", "Học bổng Seoul City", "Học bổng dành cho sinh viên quốc tế"],
        popularFor: ["Khoa học đô thị", "Kinh tế", "Quản lý công", "Khoa học máy tính", "Kỹ thuật môi trường"],
        studentCount: "13,000+",
        internationalStudentRatio: "8%",
        vietnameseStudents: "Có sinh viên Việt Nam theo học",
        address: "163 Seoulsiripdae-ro, Dongdaemun-gu, Seoul",
        image: "https://upload.wikimedia.org/wikipedia/en/1/19/University_of_Seoul_emblem.svg",
        coordinates: { lat: 37.5832, lng: 127.0584 },
        featured: false,
        tags: ["top-20", "cong-lap", "hoc-phi-thap"]
    },

    // ============ GYEONGGI & INCHEON (Vùng thủ đô mở rộng) ============
    {
        id: "ajou-university",
        name: "Đại học Ajou",
        nameKr: "아주대학교",
        nameEn: "Ajou University",
        region: "Gyeonggi",
        type: "Tư thục",
        tier: "Top 20",
        ranking: 17,
        established: 1973,
        website: "http://www.ajou.ac.kr",
        description: "Trường đại học tư thục danh tiếng tại Suwon, nổi tiếng với ngành Y khoa, Kỹ thuật và Kinh doanh. Có liên kết chặt chẽ với Samsung.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "5,000 - 9,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3-4",
        englishRequired: "IELTS 6.0+ / TOEFL 80+",
        scholarship: ["Học bổng Ajou Global", "Học bổng Ajou Excellence", "Học bổng dành cho sinh viên quốc tế"],
        popularFor: ["Y khoa", "Kỹ thuật", "Kinh doanh quốc tế", "Khoa học máy tính", "Kỹ thuật hóa học"],
        studentCount: "14,000+",
        internationalStudentRatio: "12%",
        vietnameseStudents: "Đông đảo, đặc biệt ngành Y và Kỹ thuật",
        address: "206 Worldcup-ro, Yeongtong-gu, Suwon, Gyeonggi-do",
        image: "https://upload.wikimedia.org/wikipedia/en/e/e9/Ajou_University_emblem.svg",
        coordinates: { lat: 37.2847, lng: 127.0456 },
        featured: false,
        tags: ["top-20", "tu-thuc", "y-khoa", "ky-thuat", "suwon"]
    },
    {
        id: "inha-university",
        name: "Đại học Inha",
        nameKr: "인하대학교",
        nameEn: "Inha University",
        region: "Incheon",
        type: "Tư thục",
        tier: "Top 20",
        ranking: 18,
        established: 1954,
        website: "http://www.inha.ac.kr",
        description: "Trường đại học tư thục hàng đầu tại Incheon, nổi tiếng với các ngành Kỹ thuật Hàng không, Cơ khí và Logistics.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "5,000 - 8,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3-4",
        englishRequired: "IELTS 5.5+ / TOEFL 80+",
        scholarship: ["Học bổng Inha Global", "Học bổng Inha Dream", "Học bổng dành cho sinh viên quốc tế"],
        popularFor: ["Kỹ thuật hàng không", "Cơ khí", "Logistics", "Khoa học biển", "Kinh doanh quốc tế"],
        studentCount: "22,000+",
        internationalStudentRatio: "10%",
        vietnameseStudents: "Nhiều sinh viên theo học ngành Kỹ thuật và Logistics",
        address: "100 Inha-ro, Michuhol-gu, Incheon",
        image: "https://upload.wikimedia.org/wikipedia/en/9/90/Inha_University_emblem.svg",
        coordinates: { lat: 37.4479, lng: 126.6536 },
        featured: false,
        tags: ["top-20", "tu-thuc", "hang-khong", "logistics", "incheon"]
    },

    // ============ BUSAN (Thành phố cảng lớn nhất miền Nam) ============
    {
        id: "pusan-national-university",
        name: "Đại học Quốc gia Pusan",
        nameKr: "부산대학교",
        nameEn: "Pusan National University (PNU)",
        region: "Busan",
        type: "Công lập",
        tier: "Top 10",
        ranking: 19,
        established: 1946,
        website: "http://www.pusan.ac.kr",
        description: "Trường đại học quốc gia hàng đầu tại Busan, một trong những trường công lập lớn nhất và uy tín nhất Hàn Quốc. Đặc biệt mạnh về Kỹ thuật và Khoa học tự nhiên.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "3,000 - 5,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3-4",
        englishRequired: "IELTS 5.5+ / TOEFL 80+",
        scholarship: ["Học bổng PNU Global", "Học bổng GKS (Chính phủ)", "Học bổng dành cho sinh viên quốc tế xuất sắc"],
        popularFor: ["Kỹ thuật cơ khí", "Khoa học tự nhiên", "Kinh tế", "Kiến trúc hàng hải", "Y khoa"],
        studentCount: "30,000+",
        internationalStudentRatio: "10%",
        vietnameseStudents: "Cộng đồng sinh viên Việt Nam lớn, chi phí sinh hoạt thấp",
        address: "2 Busandaehak-ro 63beon-gil, Geumjeong-gu, Busan",
        image: "https://upload.wikimedia.org/wikipedia/en/5/5c/Pusan_National_University_emblem.svg",
        coordinates: { lat: 35.2336, lng: 129.0825 },
        featured: true,
        tags: ["top-10", "cong-lap", "busan", "ky-thuat", "hoc-phi-thap"]
    },
    {
        id: "dong-a-university",
        name: "Đại học Dong-A",
        nameKr: "동아대학교",
        nameEn: "Dong-A University",
        region: "Busan",
        type: "Tư thục",
        tier: "Top 30",
        ranking: 20,
        established: 1947,
        website: "http://www.donga.ac.kr",
        description: "Trường đại học tư thục danh tiếng tại Busan, nổi tiếng với ngành Luật, Kỹ thuật và Khoa học xã hội.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "4,000 - 7,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3",
        englishRequired: "IELTS 5.5+ / TOEFL 80+",
        scholarship: ["Học bổng Dong-A Global", "Học bổng Dong-A International"],
        popularFor: ["Luật", "Kỹ thuật", "Khoa học xã hội", "Kinh doanh"],
        studentCount: "20,000+",
        internationalStudentRatio: "8%",
        vietnameseStudents: "Có sinh viên Việt Nam",
        address: "37 Nakdong-daero 550beon-gil, Saha-gu, Busan",
        image: "https://upload.wikimedia.org/wikipedia/en/f/f4/Dong-A_University_emblem.svg",
        coordinates: { lat: 35.1014, lng: 128.9643 },
        featured: false,
        tags: ["busan", "tu-thuc", "luat"]
    },

    // ============ DAEGU & GYEONGBUK ============
    {
        id: "kyungpook-national-university",
        name: "Đại học Quốc gia Kyungpook",
        nameKr: "경북대학교",
        nameEn: "Kyungpook National University (KNU)",
        region: "Daegu",
        type: "Công lập",
        tier: "Top 20",
        ranking: 21,
        established: 1946,
        website: "http://www.knu.ac.kr",
        description: "Trường đại học quốc gia hàng đầu tại Daegu, trung tâm giáo dục và nghiên cứu của vùng Gyeongsangbuk-do.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "3,000 - 5,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3-4",
        englishRequired: "IELTS 5.5+ / TOEFL 80+",
        scholarship: ["Học bổng KNU Global", "Học bổng GKS", "Học bổng dành cho sinh viên quốc tế"],
        popularFor: ["Kỹ thuật điện tử", "Khoa học máy tính", "Y khoa", "Nông nghiệp", "Kinh tế"],
        studentCount: "28,000+",
        internationalStudentRatio: "9%",
        vietnameseStudents: "Có cộng đồng sinh viên Việt Nam",
        address: "80 Daehak-ro, Buk-gu, Daegu",
        image: "https://upload.wikimedia.org/wikipedia/en/5/5f/Kyungpook_National_University_emblem.svg",
        coordinates: { lat: 35.8910, lng: 128.6097 },
        featured: false,
        tags: ["top-20", "cong-lap", "daegu", "hoc-phi-thap"]
    },
    {
        id: "yeungnam-university",
        name: "Đại học Yeungnam",
        nameKr: "영남대학교",
        nameEn: "Yeungnam University",
        region: "Gyeongbuk",
        type: "Tư thục",
        tier: "Top 30",
        ranking: 22,
        established: 1947,
        website: "http://www.yu.ac.kr",
        description: "Trường đại học tư thục lớn tại Gyeongsan, Gyeongbuk, với thế mạnh về Kỹ thuật và Khoa học.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "4,000 - 6,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3",
        englishRequired: "IELTS 5.5+",
        scholarship: ["Học bổng Yeungnam Global", "Học bổng Yeungnam Dream"],
        popularFor: ["Kỹ thuật", "Khoa học", "Kinh doanh", "Ngôn ngữ Hàn"],
        studentCount: "23,000+",
        internationalStudentRatio: "8%",
        vietnameseStudents: "Có sinh viên Việt Nam",
        address: "280 Daehak-ro, Gyeongsan-si, Gyeongsangbuk-do",
        image: "https://upload.wikimedia.org/wikipedia/en/7/7b/Yeungnam_University_emblem.svg",
        coordinates: { lat: 35.8242, lng: 128.7554 },
        featured: false,
        tags: ["tu-thuc", "gyeongbuk", "ky-thuat"]
    },

    // ============ DAEJEON & CHUNGCHEONG ============
    {
        id: "kaist",
        name: "KAIST (Viện Khoa học và Công nghệ Tiên tiến Hàn Quốc)",
        nameKr: "한국과학기술원",
        nameEn: "KAIST - Korea Advanced Institute of Science & Technology",
        region: "Daejeon",
        type: "Công lập",
        tier: "Đặc biệt",
        ranking: 23,
        established: 1971,
        website: "http://www.kaist.ac.kr",
        description: "Viện nghiên cứu và đào tạo khoa học kỹ thuật hàng đầu Hàn Quốc, được mệnh danh là 'MIT của châu Á'. Xếp hạng cao trong các bảng xếp hạng đại học thế giới.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "3,500 - 6,000 USD/năm",
        language: ["Tiếng Anh", "Tiếng Hàn"],
        topikRequired: "TOPIK 3 (không bắt buộc với chương trình tiếng Anh)",
        englishRequired: "IELTS 6.5+ / TOEFL 90+ (bắt buộc)",
        scholarship: ["Học bổng KAIST Global", "Học bổng KAIST International", "Học bổng toàn phần cho sinh viên xuất sắc"],
        popularFor: ["Khoa học máy tính", "Kỹ thuật điện tử", "Kỹ thuật hóa học", "Vật lý", "Toán học", "Kỹ thuật sinh học"],
        studentCount: "14,000+",
        internationalStudentRatio: "15%",
        vietnameseStudents: "Cộng đồng sinh viên Việt Nam xuất sắc, đa số học bổng toàn phần",
        address: "291 Daehak-ro, Yuseong-gu, Daejeon",
        image: "https://upload.wikimedia.org/wikipedia/en/b/b0/KAIST_emblem.svg",
        coordinates: { lat: 36.3728, lng: 127.3608 },
        featured: true,
        tags: ["dac-biet", "cong-lap", "khoa-hoc", "cong-nghe", "hoc-bong-toan-phan", "daejeon"]
    },
    {
        id: "chungnam-national-university",
        name: "Đại học Quốc gia Chungnam",
        nameKr: "충남대학교",
        nameEn: "Chungnam National University (CNU)",
        region: "Daejeon",
        type: "Công lập",
        tier: "Top 30",
        ranking: 24,
        established: 1952,
        website: "http://www.cnu.ac.kr",
        description: "Trường đại học quốc gia hàng đầu tại Daejeon, trung tâm giáo dục và nghiên cứu của vùng Chungcheongnam-do.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "3,000 - 5,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3",
        englishRequired: "IELTS 5.5+ / TOEFL 80+",
        scholarship: ["Học bổng CNU Global", "Học bổng GKS", "Học bổng dành cho sinh viên quốc tế"],
        popularFor: ["Kỹ thuật", "Khoa học tự nhiên", "Y khoa", "Kinh tế", "Nông nghiệp"],
        studentCount: "25,000+",
        internationalStudentRatio: "8%",
        vietnameseStudents: "Có sinh viên Việt Nam theo học",
        address: "99 Daehak-ro, Yuseong-gu, Daejeon",
        image: "https://upload.wikimedia.org/wikipedia/en/9/99/Chungnam_National_University_emblem.svg",
        coordinates: { lat: 36.3641, lng: 127.3472 },
        featured: false,
        tags: ["cong-lap", "daejeon", "hoc-phi-thap"]
    },

    // ============ GANGWON ============
    {
        id: "kangwon-national-university",
        name: "Đại học Quốc gia Kangwon",
        nameKr: "강원대학교",
        nameEn: "Kangwon National University (KNU)",
        region: "Gangwon",
        type: "Công lập",
        tier: "Top 30",
        ranking: 25,
        established: 1947,
        website: "http://www.kangwon.ac.kr",
        description: "Trường đại học quốc gia hàng đầu tại tỉnh Gangwon, nổi tiếng với các ngành Nông nghiệp, Lâm nghiệp và Khoa học môi trường.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "2,500 - 4,500 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3",
        englishRequired: "IELTS 5.5+ / TOEFL 80+",
        scholarship: ["Học bổng KNU Global", "Học bổng GKS", "Học bổng dành cho sinh viên quốc tế"],
        popularFor: ["Nông nghiệp", "Lâm nghiệp", "Khoa học môi trường", "Du lịch", "Kỹ thuật"],
        studentCount: "22,000+",
        internationalStudentRatio: "7%",
        vietnameseStudents: "Có sinh viên Việt Nam",
        address: "1 Gangwondaehak-gil, Chuncheon-si, Gangwon-do",
        image: "https://upload.wikimedia.org/wikipedia/en/9/97/Kangwon_National_University_emblem.svg",
        coordinates: { lat: 37.8706, lng: 127.7441 },
        featured: false,
        tags: ["cong-lap", "gangwon", "nong-nghiep", "hoc-phi-thap"]
    },

    // ============ JEONLLA ============
    {
        id: "chonnam-national-university",
        name: "Đại học Quốc gia Chonnam",
        nameKr: "전남대학교",
        nameEn: "Chonnam National University (CNU)",
        region: "Jeonnam",
        type: "Công lập",
        tier: "Top 20",
        ranking: 26,
        established: 1952,
        website: "http://www.jnu.ac.kr",
        description: "Trường đại học quốc gia hàng đầu tại Gwangju và Jeonnam, với thế mạnh về Y khoa, Kỹ thuật và Khoa học xã hội.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "3,000 - 5,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3-4",
        englishRequired: "IELTS 5.5+ / TOEFL 80+",
        scholarship: ["Học bổng CNU Global", "Học bổng GKS", "Học bổng dành cho sinh viên quốc tế xuất sắc"],
        popularFor: ["Y khoa", "Kỹ thuật", "Khoa học xã hội", "Kinh tế", "Ngôn ngữ Hàn"],
        studentCount: "27,000+",
        internationalStudentRatio: "9%",
        vietnameseStudents: "Cộng đồng sinh viên Việt Nam đông đảo",
        address: "77 Yongbong-ro, Buk-gu, Gwangju",
        image: "https://upload.wikimedia.org/wikipedia/en/5/58/Chonnam_National_University_emblem.svg",
        coordinates: { lat: 35.1848, lng: 126.9097 },
        featured: false,
        tags: ["top-20", "cong-lap", "gwangju", "y-khoa"]
    },
    {
        id: "chonbuk-national-university",
        name: "Đại học Quốc gia Chonbuk",
        nameKr: "전북대학교",
        nameEn: "Jeonbuk National University (JBNU)",
        region: "Jeonbuk",
        type: "Công lập",
        tier: "Top 30",
        ranking: 27,
        established: 1947,
        website: "http://www.jbnu.ac.kr",
        description: "Trường đại học quốc gia hàng đầu tại Jeonju, Jeonbuk, trung tâm giáo dục của vùng Tây Nam Hàn Quốc.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "3,000 - 5,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3",
        englishRequired: "IELTS 5.5+ / TOEFL 80+",
        scholarship: ["Học bổng JBNU Global", "Học bổng GKS", "Học bổng dành cho sinh viên quốc tế"],
        popularFor: ["Kỹ thuật", "Nông nghiệp", "Khoa học thực phẩm", "Kinh tế", "Ngôn ngữ Hàn"],
        studentCount: "22,000+",
        internationalStudentRatio: "8%",
        vietnameseStudents: "Có sinh viên Việt Nam theo học",
        address: "567 Baekje-daero, Deokjin-gu, Jeonju-si, Jeollabuk-do",
        image: "https://upload.wikimedia.org/wikipedia/en/4/4d/Chonbuk_National_University_emblem.svg",
        coordinates: { lat: 35.8459, lng: 127.1292 },
        featured: false,
        tags: ["cong-lap", "jeonbuk", "nong-nghiep"]
    },

    // ============ JEJU ============
    {
        id: "jeju-national-university",
        name: "Đại học Quốc gia Jeju",
        nameKr: "제주대학교",
        nameEn: "Jeju National University",
        region: "Jeju",
        type: "Công lập",
        tier: "Top 40",
        ranking: 28,
        established: 1952,
        website: "http://www.jejunu.ac.kr",
        description: "Trường đại học duy nhất tại đảo Jeju xinh đẹp, nổi tiếng với các ngành Du lịch, Khoa học biển và Nông nghiệp nhiệt đới.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "2,500 - 4,500 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3",
        englishRequired: "IELTS 5.5+ / TOEFL 80+",
        scholarship: ["Học bổng JNU Global", "Học bổng GKS", "Học bổng dành cho sinh viên quốc tế"],
        popularFor: ["Du lịch", "Khoa học biển", "Nông nghiệp", "Kỹ thuật môi trường", "Ngôn ngữ Hàn"],
        studentCount: "15,000+",
        internationalStudentRatio: "7%",
        vietnameseStudents: "Có cộng đồng nhỏ sinh viên Việt Nam",
        address: "102 Jejudaehak-ro, Jeju-si, Jeju-do",
        image: "https://upload.wikimedia.org/wikipedia/en/8/83/Jeju_National_University_emblem.svg",
        coordinates: { lat: 33.4549, lng: 126.5598 },
        featured: false,
        tags: ["cong-lap", "jeju", "du-lich", "khoa-hoc-bien"]
    },

    // ============ CÁC TRƯỜNG NGHỆ THUẬT & CHUYÊN NGÀNH ============
    {
        id: "korea-national-university-of-arts",
        name: "Đại học Nghệ thuật Quốc gia Hàn Quốc (K-Arts)",
        nameKr: "한국예술종합학교",
        nameEn: "Korea National University of Arts (K-Arts)",
        region: "Seoul",
        type: "Công lập",
        tier: "Chuyên ngành",
        ranking: 29,
        established: 1993,
        website: "http://www.karts.ac.kr",
        description: "Trường đại học nghệ thuật quốc gia hàng đầu Hàn Quốc, đào tạo chuyên sâu về Âm nhạc, Múa, Điện ảnh, Sân khấu và Mỹ thuật.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ"],
        tuition: "3,000 - 5,000 USD/năm",
        language: ["Tiếng Hàn"],
        topikRequired: "TOPIK 4",
        englishRequired: "Không yêu cầu",
        scholarship: ["Học bổng K-Arts Global", "Học bổng dành cho sinh viên nghệ thuật xuất sắc"],
        popularFor: ["Âm nhạc cổ điển", "Múa đương đại", "Điện ảnh", "Sân khấu", "Mỹ thuật"],
        studentCount: "3,500+",
        internationalStudentRatio: "5%",
        vietnameseStudents: "Ít, yêu cầu năng khiếu cao",
        address: "146-37 Anam-dong, Seongbuk-gu, Seoul",
        image: "https://upload.wikimedia.org/wikipedia/en/8/8a/Korea_National_University_of_Arts_emblem.svg",
        coordinates: { lat: 37.5949, lng: 127.0391 },
        featured: false,
        tags: ["cong-lap", "nghe-thuat", "chuyen-nganh"]
    },
    {
        id: "postech",
        name: "POSTECH (Đại học Khoa học và Công nghệ Pohang)",
        nameKr: "포항공과대학교",
        nameEn: "POSTECH",
        region: "Gyeongbuk",
        type: "Tư thục",
        tier: "Đặc biệt",
        ranking: 30,
        established: 1986,
        website: "http://www.postech.ac.kr",
        description: "Một trong những trường khoa học kỹ thuật hàng đầu Hàn Quốc, được thành lập bởi tập đoàn POSCO. Nổi tiếng với nghiên cứu Vật liệu và Kỹ thuật.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "4,000 - 7,000 USD/năm",
        language: ["Tiếng Anh", "Tiếng Hàn"],
        topikRequired: "TOPIK 3 (không bắt buộc)",
        englishRequired: "IELTS 6.5+ / TOEFL 90+ (bắt buộc cho chương trình tiếng Anh)",
        scholarship: ["Học bổng POSTECH Global", "Học bổng POSCO", "Học bổng toàn phần cho sinh viên xuất sắc"],
        popularFor: ["Khoa học vật liệu", "Kỹ thuật hóa học", "Vật lý", "Khoa học máy tính", "Kỹ thuật cơ khí"],
        studentCount: "4,000+",
        internationalStudentRatio: "12%",
        vietnameseStudents: "Có sinh viên Việt Nam xuất sắc với học bổng",
        address: "77 Cheongam-ro, Nam-gu, Pohang, Gyeongsangbuk-do",
        image: "https://upload.wikimedia.org/wikipedia/en/b/be/POSTECH_emblem.svg",
        coordinates: { lat: 36.0138, lng: 129.3256 },
        featured: false,
        tags: ["dac-biet", "tu-thuc", "khoa-hoc", "cong-nghe", "pohang"]
    },
    {
        id: "unist",
        name: "UNIST (Viện Khoa học và Công nghệ Quốc gia Ulsan)",
        nameKr: "울산과학기술원",
        nameEn: "Ulsan National Institute of Science and Technology (UNIST)",
        region: "Ulsan",
        type: "Công lập",
        tier: "Đặc biệt",
        ranking: 31,
        established: 2007,
        website: "http://www.unist.ac.kr",
        description: "Viện khoa học công nghệ hàng đầu tại Ulsan, trung tâm công nghiệp lớn của Hàn Quốc. Nổi tiếng với nghiên cứu Năng lượng và Kỹ thuật hóa học.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "3,500 - 6,000 USD/năm",
        language: ["Tiếng Anh", "Tiếng Hàn"],
        topikRequired: "TOPIK 3 (không bắt buộc)",
        englishRequired: "IELTS 6.0+ / TOEFL 85+ (bắt buộc)",
        scholarship: ["Học bổng UNIST Global", "Học bổng toàn phần cho sinh viên xuất sắc"],
        popularFor: ["Kỹ thuật năng lượng", "Kỹ thuật hóa học", "Khoa học vật liệu", "Kỹ thuật cơ khí", "Khoa học máy tính"],
        studentCount: "5,500+",
        internationalStudentRatio: "14%",
        vietnameseStudents: "Có sinh viên Việt Nam với học bổng",
        address: "50 UNIST-gil, Eonyang-eup, Ulju-gun, Ulsan",
        image: "https://upload.wikimedia.org/wikipedia/en/7/7a/UNIST_emblem.svg",
        coordinates: { lat: 35.5769, lng: 129.1898 },
        featured: false,
        tags: ["dac-biet", "cong-lap", "khoa-hoc", "nang-luong", "ulsan"]
    },
    {
        id: "dgist",
        name: "DGIST (Viện Khoa học và Công nghệ Daegu Gyeongbuk)",
        nameKr: "대구경북과학기술원",
        nameEn: "Daegu Gyeongbuk Institute of Science and Technology (DGIST)",
        region: "Daegu",
        type: "Công lập",
        tier: "Đặc biệt",
        ranking: 32,
        established: 2004,
        website: "http://www.dgist.ac.kr",
        description: "Viện nghiên cứu khoa học công nghệ tại Daegu, tập trung vào Khoa học não bộ, Robot và Năng lượng tái tạo.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ"],
        tuition: "3,500 - 6,000 USD/năm",
        language: ["Tiếng Anh", "Tiếng Hàn"],
        topikRequired: "TOPIK 3 (không bắt buộc)",
        englishRequired: "IELTS 6.0+ / TOEFL 85+",
        scholarship: ["Học bổng DGIST Global", "Học bổng toàn phần cho sinh viên xuất sắc"],
        popularFor: ["Khoa học não bộ", "Robot", "Năng lượng tái tạo", "Khoa học máy tính", "Kỹ thuật y sinh"],
        studentCount: "2,500+",
        internationalStudentRatio: "12%",
        vietnameseStudents: "Có một số sinh viên Việt Nam",
        address: "333 Techno Jungang-daero, Hyeonpung-eup, Dalseong-gun, Daegu",
        image: "https://upload.wikimedia.org/wikipedia/en/5/53/DGIST_emblem.svg",
        coordinates: { lat: 35.7354, lng: 128.4618 },
        featured: false,
        tags: ["dac-biet", "cong-lap", "khoa-hoc", "robot", "daegu"]
    },
    {
        id: "gist",
        name: "GIST (Viện Khoa học và Công nghệ Gwangju)",
        nameKr: "광주과학기술원",
        nameEn: "Gwangju Institute of Science and Technology (GIST)",
        region: "Gwangju",
        type: "Công lập",
        tier: "Đặc biệt",
        ranking: 33,
        established: 1993,
        website: "http://www.gist.ac.kr",
        description: "Viện nghiên cứu khoa học công nghệ hàng đầu tại Gwangju, nổi tiếng với các chương trình đào tạo sau đại học xuất sắc.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ"],
        tuition: "3,500 - 6,000 USD/năm",
        language: ["Tiếng Anh", "Tiếng Hàn"],
        topikRequired: "TOPIK 3 (không bắt buộc)",
        englishRequired: "IELTS 6.0+ / TOEFL 85+ (bắt buộc)",
        scholarship: ["Học bổng GIST Global", "Học bổng toàn phần cho sinh viên xuất sắc"],
        popularFor: ["Khoa học máy tính", "Kỹ thuật điện tử", "Khoa học môi trường", "Kỹ thuật y sinh", "Vật lý"],
        studentCount: "2,000+",
        internationalStudentRatio: "15%",
        vietnameseStudents: "Có sinh viên Việt Nam",
        address: "123 Cheomdangwagi-ro, Buk-gu, Gwangju",
        image: "https://upload.wikimedia.org/wikipedia/en/a/a0/GIST_emblem.svg",
        coordinates: { lat: 35.2294, lng: 126.8390 },
        featured: false,
        tags: ["dac-biet", "cong-lap", "khoa-hoc", "gwangju"]
    },

    // ============ THÊM CÁC TRƯỜNG KHÁC ============
    {
        id: "sunchon-national-university",
        name: "Đại học Quốc gia Sunchon",
        nameKr: "순천대학교",
        nameEn: "Sunchon National University",
        region: "Jeonnam",
        type: "Công lập",
        tier: "Top 50",
        ranking: 34,
        established: 1935,
        website: "http://www.scnu.ac.kr",
        description: "Trường đại học quốc gia tại Sunchon, Jeonnam, với thế mạnh về Nông nghiệp và Khoa học đời sống.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ"],
        tuition: "2,500 - 4,000 USD/năm",
        language: ["Tiếng Hàn"],
        topikRequired: "TOPIK 3",
        englishRequired: "Không yêu cầu",
        scholarship: ["Học bổng SCNU Global", "Học bổng GKS"],
        popularFor: ["Nông nghiệp", "Khoa học đời sống", "Ngôn ngữ Hàn", "Kinh tế"],
        studentCount: "9,000+",
        internationalStudentRatio: "6%",
        vietnameseStudents: "Có sinh viên Việt Nam",
        address: "255 Jungang-ro, Sunchon-si, Jeollanam-do",
        image: null,
        coordinates: { lat: 34.9650, lng: 127.4962 },
        featured: false,
        tags: ["cong-lap", "jeonnam", "nong-nghiep"]
    },
    {
        id: "handong-global-university",
        name: "Đại học Handong Global",
        nameKr: "한동대학교",
        nameEn: "Handong Global University",
        region: "Gyeongbuk",
        type: "Tư thục",
        tier: "Top 40",
        ranking: 35,
        established: 1995,
        website: "http://www.handong.edu",
        description: "Trường đại học tư thục toàn cầu tại Pohang, nổi tiếng với chương trình giảng dạy bằng tiếng Anh và môi trường quốc tế hóa cao.",
        programs: ["Cử nhân", "Thạc sĩ", "Trao đổi"],
        tuition: "5,000 - 7,000 USD/năm",
        language: ["Tiếng Anh", "Tiếng Hàn"],
        topikRequired: "TOPIK 3",
        englishRequired: "IELTS 6.0+ / TOEFL 80+",
        scholarship: ["Học bổng Handong Global", "Học bổng Handong International"],
        popularFor: ["Kinh doanh quốc tế", "Quan hệ quốc tế", "Phát triển quốc tế", "Công nghệ thông tin"],
        studentCount: "4,500+",
        internationalStudentRatio: "20%",
        vietnameseStudents: "Có sinh viên Việt Nam",
        address: "558 Handong-ro, Heunghae-eup, Buk-gu, Pohang, Gyeongsangbuk-do",
        image: null,
        coordinates: { lat: 36.0736, lng: 129.4016 },
        featured: false,
        tags: ["tu-thuc", "quoc-te", "tieng-anh"]
    },
    {
        id: "pukyong-national-university",
        name: "Đại học Quốc gia Pukyong",
        nameKr: "부경대학교",
        nameEn: "Pukyong National University (PKNU)",
        region: "Busan",
        type: "Công lập",
        tier: "Top 30",
        ranking: 36,
        established: 1996,
        website: "http://www.pknu.ac.kr",
        description: "Trường đại học quốc gia tại Busan, được hình thành từ sự hợp nhất của hai trường đại học ngư nghiệp và kỹ thuật.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "3,000 - 5,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3",
        englishRequired: "IELTS 5.5+ / TOEFL 80+",
        scholarship: ["Học bổng PKNU Global", "Học bổng dành cho sinh viên quốc tế"],
        popularFor: ["Khoa học biển", "Ngư nghiệp", "Kỹ thuật", "Kinh tế biển", "Kiến trúc hàng hải"],
        studentCount: "21,000+",
        internationalStudentRatio: "8%",
        vietnameseStudents: "Có sinh viên Việt Nam",
        address: "45 Yongso-ro, Nam-gu, Busan",
        image: "https://upload.wikimedia.org/wikipedia/en/f/f3/Pukyong_National_University_emblem.svg",
        coordinates: { lat: 35.1352, lng: 129.1027 },
        featured: false,
        tags: ["cong-lap", "busan", "khoa-hoc-bien", "ngu-nghiep"]
    },
    {
        id: "korea-national-university-of-education",
        name: "Đại học Sư phạm Quốc gia Hàn Quốc",
        nameKr: "한국교원대학교",
        nameEn: "Korea National University of Education (KNUE)",
        region: "Chungbuk",
        type: "Công lập",
        tier: "Chuyên ngành",
        ranking: 37,
        established: 1984,
        website: "http://www.knue.ac.kr",
        description: "Trường đại học sư phạm hàng đầu Hàn Quốc, đào tạo giáo viên chất lượng cao cho hệ thống giáo dục quốc gia.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ"],
        tuition: "2,500 - 4,000 USD/năm",
        language: ["Tiếng Hàn"],
        topikRequired: "TOPIK 4",
        englishRequired: "IELTS 5.5+",
        scholarship: ["Học bổng KNUE Global", "Học bổng GKS"],
        popularFor: ["Sư phạm tiếng Hàn", "Sư phạm tiếng Anh", "Giáo dục tiểu học", "Giáo dục đặc biệt"],
        studentCount: "6,000+",
        internationalStudentRatio: "4%",
        vietnameseStudents: "Có một số sinh viên Việt Nam ngành Sư phạm tiếng Hàn",
        address: "250 Taeseongtabyeon-ro, Gangnae-myeon, Heungdeok-gu, Cheongju-si, Chungcheongbuk-do",
        image: null,
        coordinates: { lat: 36.6181, lng: 127.3412 },
        featured: false,
        tags: ["cong-lap", "su-pham", "chuyen-nganh"]
    },
    {
        id: "duksung-womens-university",
        name: "Đại học Nữ Duksung",
        nameKr: "덕성여자대학교",
        nameEn: "Duksung Women's University",
        region: "Seoul",
        type: "Tư thục",
        tier: "Top 50",
        ranking: 38,
        established: 1920,
        website: "http://www.duksung.ac.kr",
        description: "Trường đại học nữ tại Seoul, nổi tiếng với chương trình đào tạo Dược, Khoa học xã hội và Nghệ thuật.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ"],
        tuition: "4,000 - 6,000 USD/năm",
        language: ["Tiếng Hàn"],
        topikRequired: "TOPIK 3",
        englishRequired: "IELTS 5.5+",
        scholarship: ["Học bổng Duksung Global"],
        popularFor: ["Dược", "Khoa học xã hội", "Ngôn ngữ Hàn", "Thiết kế"],
        studentCount: "8,000+",
        internationalStudentRatio: "5%",
        vietnameseStudents: "Có sinh viên Việt Nam",
        address: "33 Samyang-ro 144-gil, Dobong-gu, Seoul",
        image: null,
        coordinates: { lat: 37.6449, lng: 127.0347 },
        featured: false,
        tags: ["tu-thuc", "nu-sinh", "duoc"]
    },
    {
        id: "myongji-university",
        name: "Đại học Myongji",
        nameKr: "명지대학교",
        nameEn: "Myongji University",
        region: "Seoul",
        type: "Tư thục",
        tier: "Top 40",
        ranking: 39,
        established: 1948,
        website: "http://www.mju.ac.kr",
        description: "Trường đại học tư thục với hai cơ sở tại Seoul và Yongin, nổi tiếng với ngành Kỹ thuật và Khoa học xã hội.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "4,500 - 7,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3",
        englishRequired: "IELTS 5.5+ / TOEFL 80+",
        scholarship: ["Học bổng Myongji Global", "Học bổng Myongji International"],
        popularFor: ["Kỹ thuật", "Khoa học xã hội", "Kinh doanh", "Kiến trúc"],
        studentCount: "15,000+",
        internationalStudentRatio: "7%",
        vietnameseStudents: "Có sinh viên Việt Nam",
        address: "34 Geobukgol-ro, Seodaemun-gu, Seoul",
        image: null,
        coordinates: { lat: 37.5812, lng: 126.9241 },
        featured: false,
        tags: ["tu-thuc", "ky-thuat"]
    },
    {
        id: "dankook-university",
        name: "Đại học Dankook",
        nameKr: "단국대학교",
        nameEn: "Dankook University",
        region: "Gyeonggi",
        type: "Tư thục",
        tier: "Top 30",
        ranking: 40,
        established: 1947,
        website: "http://www.dankook.ac.kr",
        description: "Trường đại học tư thục với cơ sở chính tại Yongin, nổi tiếng với ngành Y khoa, Kỹ thuật và Nghệ thuật.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "4,500 - 8,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3-4",
        englishRequired: "IELTS 5.5+ / TOEFL 80+",
        scholarship: ["Học bổng Dankook Global", "Học bổng Dankook Dream"],
        popularFor: ["Y khoa", "Kỹ thuật", "Nghệ thuật", "Kinh doanh", "Ngôn ngữ Hàn"],
        studentCount: "20,000+",
        internationalStudentRatio: "8%",
        vietnameseStudents: "Có sinh viên Việt Nam",
        address: "152 Jukjeon-ro, Suji-gu, Yongin-si, Gyeonggi-do",
        image: null,
        coordinates: { lat: 37.3234, lng: 127.1284 },
        featured: false,
        tags: ["tu-thuc", "gyeonggi", "y-khoa"]
    },
    {
        id: "catholic-university-of-korea",
        name: "Đại học Công giáo Hàn Quốc",
        nameKr: "가톨릭대학교",
        nameEn: "The Catholic University of Korea",
        region: "Seoul",
        type: "Tư thục",
        tier: "Top 20",
        ranking: 41,
        established: 1855,
        website: "http://www.catholic.ac.kr",
        description: "Trường đại học Công giáo danh tiếng, nổi tiếng với Y khoa và các bệnh viện liên kết hàng đầu Hàn Quốc.",
        programs: ["Cử nhân", "Thạc sĩ", "Tiến sĩ", "Trao đổi"],
        tuition: "5,000 - 9,000 USD/năm",
        language: ["Tiếng Hàn", "Tiếng Anh"],
        topikRequired: "TOPIK 3-4",
        englishRequired: "IELTS 6.0+ / TOEFL 80+",
        scholarship: ["Học bổng Catholic Global", "Học bổng Catholic International"],
        popularFor: ["Y khoa", "Điều dưỡng", "Dược", "Khoa học xã hội", "Kinh doanh"],
        studentCount: "16,000+",
        internationalStudentRatio: "8%",
        vietnameseStudents: "Có sinh viên Việt Nam ngành Y và Điều dưỡng",
        address: "222 Banpo-daero, Seocho-gu, Seoul",
        image: null,
        coordinates: { lat: 37.4871, lng: 127.0034 },
        featured: false,
        tags: ["top-20", "tu-thuc", "y-khoa", "cong-giao"]
    },
    {
        id: "kookje-university",
        name: "Đại học Kookje",
        nameKr: "국제대학교",
        nameEn: "Kookje University",
        region: "Gyeongnam",
        type: "Tư thục",
        tier: "Top 50",
        ranking: 42,
        established: 1994,
        website: "http://www.kookje.ac.kr",
        description: "Trường đại học tư thục tại Gyeongnam, tập trung vào đào tạo thực hành và kỹ năng nghề nghiệp.",
        programs: ["Cử nhân", "Cao đẳng"],
        tuition: "3,000 - 5,000 USD/năm",
        language: ["Tiếng Hàn"],
        topikRequired: "TOPIK 3",
        englishRequired: "Không yêu cầu",
        scholarship: ["Học bổng Kookje Global"],
        popularFor: ["Kỹ thuật thực hành", "Du lịch", "Kinh doanh", "Ngôn ngữ Hàn"],
        studentCount: "3,000+",
        internationalStudentRatio: "10%",
        vietnameseStudents: "Có sinh viên Việt Nam",
        address: "57 Hoeyeong-ro, Pyeongtaek-si, Gyeonggi-do",
        image: null,
        coordinates: { lat: 36.9770, lng: 127.0894 },
        featured: false,
        tags: ["tu-thuc", "thuc-hanh"]
    },
    // Trường đào tạo tiếng Hàn nổi tiếng
    {
        id: "yonsei-kli",
        name: "Viện Ngôn ngữ Hàn - Đại học Yonsei",
        nameKr: "연세대학교 한국어학당",
        nameEn: "Yonsei Korean Language Institute",
        region: "Seoul",
        type: "Trung tâm Ngôn ngữ",
        tier: "Ngôn ngữ",
        ranking: 100,
        established: 1959,
        website: "http://www.yskli.com",
        description: "Viện ngôn ngữ Hàn lâu đời và danh tiếng nhất Hàn Quốc, trực thuộc Đại học Yonsei. Chương trình đào tạo tiếng Hàn chất lượng cao cho sinh viên quốc tế.",
        programs: ["Khóa học tiếng Hàn", "Khóa học ngắn hạn"],
        tuition: "3,500 - 4,500 USD/kỳ (6 tháng)",
        language: ["Tiếng Hàn"],
        topikRequired: "Không yêu cầu",
        englishRequired: "Không yêu cầu",
        scholarship: ["Học bổng dành cho học viên xuất sắc"],
        popularFor: ["Tiếng Hàn tổng quát", "Luyện thi TOPIK", "Tiếng Hàn học thuật"],
        studentCount: "2,000+ học viên/kỳ",
        internationalStudentRatio: "100%",
        vietnameseStudents: "Rất đông học viên Việt Nam theo học",
        address: "50 Yonsei-ro, Seodaemun-gu, Seoul",
        image: "https://upload.wikimedia.org/wikipedia/en/5/58/Yonsei_University_emblem.svg",
        coordinates: { lat: 37.5665, lng: 126.9390 },
        featured: false,
        tags: ["ngon-ngu", "tieng-han", "topik"]
    },
    {
        id: "snu-kli",
        name: "Viện Ngôn ngữ Hàn - Đại học Quốc gia Seoul",
        nameKr: "서울대학교 언어교육원",
        nameEn: "SNU Korean Language Institute",
        region: "Seoul",
        type: "Trung tâm Ngôn ngữ",
        tier: "Ngôn ngữ",
        ranking: 101,
        established: 1969,
        website: "http://www.snukorean.snu.ac.kr",
        description: "Viện ngôn ngữ trực thuộc Đại học Quốc gia Seoul, cung cấp chương trình đào tạo tiếng Hàn chuẩn mực và uy tín cho người nước ngoài.",
        programs: ["Khóa học tiếng Hàn", "Khóa học hè"],
        tuition: "3,200 - 4,000 USD/kỳ (6 tháng)",
        language: ["Tiếng Hàn"],
        topikRequired: "Không yêu cầu",
        englishRequired: "Không yêu cầu",
        scholarship: ["Học bổng dành cho học viên xuất sắc"],
        popularFor: ["Tiếng Hàn tổng quát", "Luyện thi TOPIK", "Tiếng Hàn học thuật"],
        studentCount: "1,500+ học viên/kỳ",
        internationalStudentRatio: "100%",
        vietnameseStudents: "Đông học viên Việt Nam",
        address: "1 Gwanak-ro, Gwanak-gu, Seoul",
        image: "https://upload.wikimedia.org/wikipedia/en/3/3c/Seoul_National_University_emblem.svg",
        coordinates: { lat: 37.4602, lng: 126.9514 },
        featured: false,
        tags: ["ngon-ngu", "tieng-han", "topik"]
    },
    {
        id: "korea-university-kli",
        name: "Viện Ngôn ngữ Hàn - Đại học Korea",
        nameKr: "고려대학교 한국어문화교육센터",
        nameEn: "Korea University Korean Language Center",
        region: "Seoul",
        type: "Trung tâm Ngôn ngữ",
        tier: "Ngôn ngữ",
        ranking: 102,
        established: 1986,
        website: "http://www.klc.korea.ac.kr",
        description: "Trung tâm ngôn ngữ Hàn trực thuộc Đại học Korea, chương trình đào tạo tiếng Hàn chuyên sâu với nhiều hoạt động văn hóa.",
        programs: ["Khóa học tiếng Hàn", "Khóa học ngắn hạn"],
        tuition: "3,200 - 4,000 USD/kỳ (6 tháng)",
        language: ["Tiếng Hàn"],
        topikRequired: "Không yêu cầu",
        englishRequired: "Không yêu cầu",
        scholarship: ["Học bổng dành cho học viên xuất sắc"],
        popularFor: ["Tiếng Hàn tổng quát", "Tiếng Hàn thương mại", "Luyện thi TOPIK"],
        studentCount: "1,200+ học viên/kỳ",
        internationalStudentRatio: "100%",
        vietnameseStudents: "Đông học viên Việt Nam",
        address: "145 Anam-ro, Seongbuk-gu, Seoul",
        image: "https://upload.wikimedia.org/wikipedia/en/7/7e/Korea_University_emblem.svg",
        coordinates: { lat: 37.5895, lng: 127.0322 },
        featured: false,
        tags: ["ngon-ngu", "tieng-han", "topik"]
    }
];

// Dữ liệu hỗ trợ
const regions = {
    "Seoul": { name: "Seoul (서울)", description: "Thủ đô Hàn Quốc - Trung tâm giáo dục, kinh tế và văn hóa", color: "#e74c3c" },
    "Gyeonggi": { name: "Gyeonggi-do (경기도)", description: "Tỉnh bao quanh Seoul - Nhiều khu công nghiệp và trường đại học", color: "#3498db" },
    "Incheon": { name: "Incheon (인천)", description: "Thành phố cảng quốc tế - Cửa ngõ vào Hàn Quốc", color: "#2ecc71" },
    "Busan": { name: "Busan (부산)", description: "Thành phố cảng lớn nhất miền Nam - Trung tâm kinh tế và du lịch", color: "#f39c12" },
    "Daegu": { name: "Daegu (대구)", description: "Thành phố lớn thứ 4 - Trung tâm dệt may và công nghiệp", color: "#9b59b6" },
    "Gyeongbuk": { name: "Gyeongsangbuk-do (경상북도)", description: "Tỉnh phía Đông Bắc - Nhiều di tích lịch sử", color: "#1abc9c" },
    "Gyeongnam": { name: "Gyeongsangnam-do (경상남도)", description: "Tỉnh phía Đông Nam - Trung tâm công nghiệp nặng", color: "#e67e22" },
    "Daejeon": { name: "Daejeon (대전)", description: "Thành phố khoa học công nghệ - Thung lũng Silicon Hàn Quốc", color: "#2980b9" },
    "Chungbuk": { name: "Chungcheongbuk-do (충청북도)", description: "Tỉnh miền Trung - Nhiều trường đại học và khu công nghiệp", color: "#8e44ad" },
    "Chungnam": { name: "Chungcheongnam-do (충청남도)", description: "Tỉnh miền Trung - Phát triển công nghiệp và nông nghiệp", color: "#27ae60" },
    "Gangwon": { name: "Gangwon-do (강원도)", description: "Tỉnh miền Đông - Núi non hùng vĩ, điểm đến du lịch nổi tiếng", color: "#16a085" },
    "Jeonnam": { name: "Jeollanam-do (전라남도)", description: "Tỉnh Tây Nam - Nông nghiệp và hải sản phong phú", color: "#d35400" },
    "Jeonbuk": { name: "Jeollabuk-do (전라북도)", description: "Tỉnh Tây Bắc - Văn hóa và ẩm thực truyền thống", color: "#c0392b" },
    "Jeju": { name: "Jeju (제주)", description: "Đảo du lịch nổi tiếng - Thiên đường nghỉ dưỡng", color: "#00b894" },
    "Ulsan": { name: "Ulsan (울산)", description: "Thành phố công nghiệp lớn - Trung tâm đóng tàu và ô tô", color: "#636e72" },
    "Gwangju": { name: "Gwangju (광주)", description: "Thành phố lớn thứ 6 - Trung tâm văn hóa và nghệ thuật", color: "#e17055" }
};

const tuitionRanges = {
    "2,500 - 4,000 USD/năm": { min: 2500, max: 4000 },
    "2,500 - 4,500 USD/năm": { min: 2500, max: 4500 },
    "3,000 - 5,000 USD/năm": { min: 3000, max: 5000 },
    "3,000 - 4,500 USD/năm": { min: 3000, max: 4500 },
    "3,200 - 4,000 USD/kỳ (6 tháng)": { min: 3200, max: 4000 },
    "3,500 - 4,500 USD/kỳ (6 tháng)": { min: 3500, max: 4500 },
    "3,500 - 6,000 USD/năm": { min: 3500, max: 6000 },
    "4,000 - 6,000 USD/năm": { min: 4000, max: 6000 },
    "4,000 - 7,000 USD/năm": { min: 4000, max: 7000 },
    "4,500 - 7,000 USD/năm": { min: 4500, max: 7000 },
    "4,500 - 8,000 USD/năm": { min: 4500, max: 8000 },
    "5,000 - 7,000 USD/năm": { min: 5000, max: 7000 },
    "5,000 - 8,000 USD/năm": { min: 5000, max: 8000 },
    "5,000 - 9,000 USD/năm": { min: 5000, max: 9000 },
    "6,000 - 10,000 USD/năm": { min: 6000, max: 10000 }
};
